title: Khiem Nguyen
logo: assets/img/profile.jpg
description: 
  Solutions Engineer Associate @ Northwestern Medicine | CS@IIT | AI/ML Enthusiast 
  <br/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <i class="fa fa-map-marker" aria-hidden="true"></i> Chicago, IL <br/>
  <i class="fa fa-linkedin-square"></i> <a href="https://www.linkedin.com/in/khiem-nguyen-19b6a8201/"> Linkedin</a> <br/>
  <i class="fa fa-envelope" aria-hidden="true"></i> knguyen22@hawk.iit.edu <br/>
  <i class="fa fa-github" aria-hidden="true"></i><a href="https://github.com/khiemnguyen22"> GitHub</a>

theme: jekyll-theme-minimal
